drop table poi_change;
create table poi_change (
osm_id bigint,
obj_type text,
uid int,
name text,
description text,
information text,
image text,
opening_hours text,
phone text,
email text,
website text,
url text,
"addr:city" text,
"addr:street" text,
"addr:postcode" text,
"addr:housenumber" text,
real_ale text,
historic text,
man_made text,
"tower:type" text,
fee text,
ref text,
wikipedia text,
"wikipedia:lt" text,
"wikipedia:en" text,
height text,
alt_name text,
"ref:lt:kpd" text,
maxspeed text,
operator text,
tourism text,
site_type text,
amenity text,
fireplace text,
highway text,
access text,
shop text,
whitewater text,
milestone text,
waterway_description text,
religion text,
denomination text,
office text,
official_name text,
"attraction:type" text,
distance text,
"natural" text,
lat real,
lon real,
x_type text -- N - new, D - deleted, C - changed
);

select addgeometrycolumn('poi_change', 'way', 4326, 'POINT', 2);

grant select on poif to tomas;
